// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountCollectionImages(arg1) {
  return window['go']['main']['App']['CountCollectionImages'](arg1);
}

export function GenerateCollage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GenerateCollage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetDefaultOutputPath() {
  return window['go']['main']['App']['GetDefaultOutputPath']();
}

export function GetImagePreview(arg1) {
  return window['go']['main']['App']['GetImagePreview'](arg1);
}

export function SelectCollectionDirectory() {
  return window['go']['main']['App']['SelectCollectionDirectory']();
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}

export function SelectTargetImage() {
  return window['go']['main']['App']['SelectTargetImage']();
}
