// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CountCollectionImages(arg1:string):Promise<number>;

export function GenerateCollage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<main.GenerateResult>;

export function GetDefaultOutputPath():Promise<string>;

export function GetImagePreview(arg1:string):Promise<string>;

export function SelectCollectionDirectory():Promise<string>;

export function SelectOutputDirectory():Promise<string>;

export function SelectTargetImage():Promise<string>;
